/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        surface: "#f8f9ff",
        "inverse-primary": "#adc6ff",
        "secondary-fixed-dim": "#4edea3",
        "secondary-fixed": "#6ffbbe",
        background: "#f8f9ff",
        primary: "#0058be",
        "tertiary-container": "#a36700",
        "surface-variant": "#d3e4fe",
        "outline-variant": "#c2c6d6",
        "on-tertiary-fixed": "#2a1700",
        "on-tertiary-container": "#fffbff",
        "surface-container-low": "#eff4ff",
        "secondary-container": "#6cf8bb",
        "inverse-on-surface": "#eaf1ff",
        "on-surface": "#0b1c30",
        outline: "#727785",
        "on-secondary-fixed": "#002113",
        "on-primary-fixed-variant": "#004395",
        "surface-tint": "#005ac2",
        "on-secondary": "#ffffff",
        "inverse-surface": "#213145",
        "on-surface-variant": "#424754",
        "on-background": "#0b1c30",
        error: "#ba1a1a",
        "surface-dim": "#cbdbf5",
        "on-tertiary": "#ffffff",
        "surface-container-highest": "#d3e4fe",
        "primary-fixed": "#d8e2ff",
        "on-primary-container": "#fefcff",
        "surface-container-lowest": "#ffffff",
        "primary-container": "#2170e4",
        "tertiary-fixed": "#ffddb8",
        "surface-container": "#e5eeff",
        "on-error": "#ffffff",
        "on-tertiary-fixed-variant": "#653e00",
        "on-secondary-container": "#00714d",
        "tertiary-fixed-dim": "#ffb95f",
        "tertiary": "#825100",
        "surface-container-high": "#dce9ff",
        "primary-fixed-dim": "#adc6ff",
        "on-primary": "#ffffff",
        secondary: "#006c49",
        "on-error-container": "#93000a",
        "on-secondary-fixed-variant": "#005236",
        "on-primary-fixed": "#001a42",
        "error-container": "#ffdad6",
        "surface-bright": "#f8f9ff",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "stack-lg": "1.5rem",
        "sidebar-width": "260px",
        "stack-md": "1rem",
        "container-max": "1440px",
        "margin-desktop": "2rem",
        "stack-sm": "0.5rem",
        "margin-mobile": "1rem",
        gutter: "1.5rem",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
      },
      fontSize: {
        "label-md": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "headline-lg": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "display-lg": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-sm": ["11px", { lineHeight: "14px", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
      },
    },
  },
  plugins: [require("@tailwindcss/forms")],
};
